#define SCREEN_WIDTH 1600
#define SCREEN_HEIGHT 900
#define FRAMERATE 1000/60

#define OUT_OF_BOUNDS_THRESHOLD 100

#define MAX_SCORE 5

#define PADDLE_WIDTH 25
#define PADDLE_HEIGHT 170
#define PADDLE_OFFSET_FROM_WALL 100
#define PADDLE_SPEED 800
#define PADDLE_SHORTENING_AMOUNT 20
#define PADDLE_EXTENDING_AMOUNT 40

#define MAX_BALL_AMOUNT 2
#define BALL_SIZE 50
#define BALL_INITIAL_SPEED 500
#define BALL_SPEED_INCREMENT 50
#define DISTANCE_TO_CENTER_LENIENCY 10
#define BALL_SPEED_TO_SPAWN_ANOTHER 700
#define BALL_SPEED_THRESHOLD_TO_SHORTEN 800

#define MAX_PARTICLE_AMOUNT 100
#define INITIAL_PARTICLE_SIZE 30
#define MAX_PARTICLE_DIR_Y 500
#define MIN_PARTICLE_DIR_X 50
#define MAX_PARTICLE_DIR_X 500
#define PARTICLE_DECAY_RATE 10
#define PARTICLE_SLOWDOWN_RATE .999

#define NUMBER_OF_CHANNELS 3

#define song "Sound\\DANCING.wav"
#define bounce "Sound\\Bounce.wav"
#define goal "Sound\\HUGO.wav"

#define MAX_OBSTACLE_AMOUNT 5